### ISSUE TITLE
Optimization Bounds

### ISSUE THREAD

**Issue by Chase1325** [nestordemeure/Simplers#7]
Hello, 

Great crate! I am a bit confused about the operation of the Simple(x) algorithm, and I believe my confusion is in the creation of the simplex from the hypercube. If I pass upper/lower bounds on variables, the algorithm converts that hypercube representation to a simplex? If so, we lose some of the search space? For example, it cannot solve the eggholder optimization problem with 2 variable bounds (-512, 512). The optimal  solution is at x=512, y=404.23, opt=-959.64. The best I can achieve is opt_cost=-946.56 @ x=481.18, y=437.23. It appears the search is never performed near x=512. Please help! :)

**Comment by nestordemeure** [comment]
Hi! Sorry for the late reply, Github didn't deemed necessary to notify me that there was an issue in one of my projects...

The algorithm takes an hypercube as input and maps it to a simplex using [this function](https://math.stackexchange.com/questions/384713/looking-for-a-nonlinear-map-from-n-dimensional-cube-to-an-n-dimensional-si/385071#385071). The mapping covers all of the space (so your minimum *will be preserved*) but it compresses parts of it in a non uniform way (some distances are shrinked more than others).

Regarding the eggholder optimization problem, I have not run any test but the most likely answer is that the point evaluated near the optimum are not good enough (due to bad luck) which leads the algorithm to never further explore that part of the input space.
